
import javax.swing.JRadioButton;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author antonio.abnma
 */
public class VisorTeclado extends javax.swing.JFrame {

    /**
     * Creates new form VisorTeclado
     */
    public VisorTeclado() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jBTGoperacoes = new javax.swing.ButtonGroup();
        jPanelOperacoes = new javax.swing.JPanel();
        jRBTadicao = new javax.swing.JRadioButton();
        jRBTsubtracao = new javax.swing.JRadioButton();
        jRBTmultiplicacao = new javax.swing.JRadioButton();
        jRBTdivisao = new javax.swing.JRadioButton();
        jPanelVisorResultado = new javax.swing.JPanel();
        jTFresultado = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jTFnumeroA = new javax.swing.JTextField();
        jTFnumeroB = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanelOperacoes.setBackground(new java.awt.Color(204, 204, 204));
        jPanelOperacoes.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Operações", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 12))); // NOI18N

        jRBTadicao.setBackground(new java.awt.Color(204, 204, 204));
        jBTGoperacoes.add(jRBTadicao);
        jRBTadicao.setText("Adição");

        jRBTsubtracao.setBackground(new java.awt.Color(204, 204, 204));
        jBTGoperacoes.add(jRBTsubtracao);
        jRBTsubtracao.setText("Subtração");

        jRBTmultiplicacao.setBackground(new java.awt.Color(204, 204, 204));
        jBTGoperacoes.add(jRBTmultiplicacao);
        jRBTmultiplicacao.setText("Multiplicação");

        jRBTdivisao.setBackground(new java.awt.Color(204, 204, 204));
        jBTGoperacoes.add(jRBTdivisao);
        jRBTdivisao.setText("Divisão");

        javax.swing.GroupLayout jPanelOperacoesLayout = new javax.swing.GroupLayout(jPanelOperacoes);
        jPanelOperacoes.setLayout(jPanelOperacoesLayout);
        jPanelOperacoesLayout.setHorizontalGroup(
            jPanelOperacoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelOperacoesLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jRBTadicao)
                .addGap(18, 18, 18)
                .addComponent(jRBTsubtracao)
                .addGap(18, 18, 18)
                .addComponent(jRBTmultiplicacao)
                .addGap(18, 18, 18)
                .addComponent(jRBTdivisao)
                .addContainerGap(26, Short.MAX_VALUE))
        );
        jPanelOperacoesLayout.setVerticalGroup(
            jPanelOperacoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelOperacoesLayout.createSequentialGroup()
                .addContainerGap(8, Short.MAX_VALUE)
                .addGroup(jPanelOperacoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRBTadicao)
                    .addComponent(jRBTsubtracao)
                    .addComponent(jRBTmultiplicacao)
                    .addComponent(jRBTdivisao))
                .addContainerGap())
        );

        jTFresultado.setEditable(false);
        jTFresultado.setBackground(new java.awt.Color(255, 255, 255));
        jTFresultado.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jTFresultado.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jTFresultado.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jTFresultado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTFresultadoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelVisorResultadoLayout = new javax.swing.GroupLayout(jPanelVisorResultado);
        jPanelVisorResultado.setLayout(jPanelVisorResultadoLayout);
        jPanelVisorResultadoLayout.setHorizontalGroup(
            jPanelVisorResultadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelVisorResultadoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTFresultado, javax.swing.GroupLayout.DEFAULT_SIZE, 396, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanelVisorResultadoLayout.setVerticalGroup(
            jPanelVisorResultadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelVisorResultadoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTFresultado, javax.swing.GroupLayout.DEFAULT_SIZE, 112, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("operandos"));

        jLabel1.setText("Numero 'a'");

        jLabel2.setText("Numero 'b'");

        jTFnumeroA.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jTFnumeroA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTFnumeroAActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jTFnumeroA, javax.swing.GroupLayout.DEFAULT_SIZE, 242, Short.MAX_VALUE)
                    .addComponent(jTFnumeroB))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTFnumeroA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTFnumeroB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 11, Short.MAX_VALUE))
        );

        jButton1.setBackground(new java.awt.Color(0, 153, 51));
        jButton1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButton1.setText("RESULTADO");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanelVisorResultado, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanelOperacoes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanelVisorResultado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(jPanelOperacoes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(22, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jTFresultadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTFresultadoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTFresultadoActionPerformed

    private void jTFnumeroAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTFnumeroAActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTFnumeroAActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        Double n1, n2, resultado = 0.0;
        n1 = Double.parseDouble(jTFnumeroA.getText());
        n2 = Double.parseDouble(jTFnumeroB.getText());
        
        if(jRBTadicao.getModel().isSelected()){
            resultado = n1 + n2;
        }else if(jRBTsubtracao.getModel().isSelected()){
            resultado = n1 - n2;
        }else if(jRBTmultiplicacao.getModel().isSelected()){
            resultado = n1 * n2;
        }else if(jRBTdivisao.getModel().isSelected()){
            resultado = n1 / n2;
        }
        jTFresultado.setText(resultado.toString());
        
        
        
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VisorTeclado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VisorTeclado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VisorTeclado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VisorTeclado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VisorTeclado().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup jBTGoperacoes;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanelOperacoes;
    private javax.swing.JPanel jPanelVisorResultado;
    private javax.swing.JRadioButton jRBTadicao;
    private javax.swing.JRadioButton jRBTdivisao;
    private javax.swing.JRadioButton jRBTmultiplicacao;
    private javax.swing.JRadioButton jRBTsubtracao;
    private javax.swing.JTextField jTFnumeroA;
    private javax.swing.JTextField jTFnumeroB;
    private javax.swing.JTextField jTFresultado;
    // End of variables declaration//GEN-END:variables
}
